import { Footer } from "@/app/components";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <h1>BIENVENIDO AL LAYOUT DE HEADER</h1>
      <div>{children}</div>
      <Footer />
    </>
  );
}
