import { Header } from "@/app/components";
import cardLayoutStyles from "./information-layout.module.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <div className={`${cardLayoutStyles.informationLayout}`}>
        <p className="bg-orange-500">LEONEIDER</p>
      </div>

      <div>{children}</div>
    </>
  );
}
